### ISSUE TITLE
Build form command line fails

### ISSUE THREAD

**Issue by vraptorche** [walt-id/waltid-idpkit#25]
When executing **gradlew build** from command line, build fails: 

Internal Error: waltid-idpkit-ui@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at Mk.getCandidates (C:\Users\vRaptor\.yarn\releases\yarn-berry.cjs:299:4306)
    at Xc.getCandidates (C:\Users\vRaptor\.yarn\releases\yarn-berry.cjs:294:4947)
    at C:\Users\vRaptor\.yarn\releases\yarn-berry.cjs:303:7643
    at Gl (C:\Users\vRaptor\.yarn\releases\yarn-berry.cjs:242:4003)
    at y (C:\Users\vRaptor\.yarn\releases\yarn-berry.cjs:303:7623)

running **yarn install** does not help

**Comment by severinstampler** [comment]
Hi @vraptorche 
I have updated the gradle build files just now. Please try if your problem is resolved.
If not, please try to delete the yarn.lock file in web/waltid-idpkit-ui and see if this solves the problem.
Thanks.
